import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { FileText, CheckCircle2, AlertTriangle, Scale, Mail } from "lucide-react";
import Footer from "@/components/Footer";

const TermsOfService = () => {
  const navigate = useNavigate();
  const lastUpdated = "March 14, 2026";
  const effectiveDate = "March 14, 2026";

  const sections = [
    {
      id: "acceptance",
      title: "1. Acceptance of Terms",
      content: `By creating an account or using HireForge ("Service"), you agree to these Terms of Service ("Terms"). If you do not agree to these Terms, do not use the Service. We may update these Terms from time to time; continued use after changes constitutes acceptance of the updated Terms. We will notify registered users of material changes via email.`,
    },
    {
      id: "service-description",
      title: "2. About the Service",
      content: `HireForge is a free AI-powered resume analysis platform. The Service includes: ATS compatibility scoring, keyword analysis, AI-powered improvement suggestions, job description targeting, job recommendations, and resume history management. HireForge is provided free of charge with no premium tiers, subscription fees, or hidden charges. We reserve the right to add optional premium features in the future, but core analysis functionality will remain free.`,
    },
    {
      id: "user-rights",
      title: "3. Your Rights & Account",
      highlight: "rights",
      content: null,
      items: [
        { title: "Account Ownership", desc: "You own your account and the data within it. Creating an account requires you to be at least 13 years old (or the minimum age in your jurisdiction)." },
        { title: "Resume Ownership", desc: "You retain full ownership of all resume content you upload. HireForge analyzes your resume but does not claim any rights to your professional history, skills, or personal information." },
        { title: "Data Export", desc: "You have the right to export your analysis data at any time. You have the right to delete your account and all associated data — we will process deletion requests within 7 business days." },
        { title: "Account Security", desc: "You are responsible for maintaining the security of your account credentials. Use a strong, unique password. Notify us immediately at security@hireforge.dev if you suspect unauthorized access." },
        { title: "Account Suspension", desc: "We reserve the right to suspend accounts that violate these Terms. We will attempt to notify you before suspension except in cases of severe abuse." },
      ],
    },
    {
      id: "acceptable-use",
      title: "4. Acceptable Use",
      content: null,
      items: [
        { title: "Permitted Use", desc: "Using HireForge for personal career advancement, resume optimization, and job searching." },
        { title: "No Commercial Resale", desc: "You may not resell, sublicense, or commercialize the HireForge service or its outputs without our written consent." },
        { title: "No Automated Scraping", desc: "Do not use bots, scrapers, or automated tools to bulk-extract analysis results, job listings, or any other data from HireForge." },
        { title: "No Abuse", desc: "Do not attempt to reverse engineer the scoring algorithm, circumvent security measures, or submit harmful content (malware disguised as resume files, etc.)." },
        { title: "Accurate Information", desc: "Do not provide false information in your resume or account. HireForge is a tool to help you present your authentic credentials more effectively — not to fabricate them." },
      ],
    },
    {
      id: "ai-disclaimers",
      title: "5. AI Analysis Disclaimer",
      content: `HireForge's ATS scores, suggestions, and job recommendations are generated by AI and are intended as guidance, not guarantees. We cannot guarantee that following our suggestions will result in ATS pass-through or job offers, as each company's ATS is configured differently and hiring decisions involve many factors beyond resume formatting. Our analysis is based on commonly documented ATS behaviors and recruiter best practices. Always use your professional judgment when applying suggestions. We update our analysis engine regularly to improve accuracy.`,
    },
    {
      id: "data-use-terms",
      title: "6. Data Use in the Service",
      content: `By uploading a resume, you grant HireForge a limited, non-exclusive license to process and analyze your resume content for the sole purpose of providing the Service to you. This license terminates when you delete your resume or close your account. We do not claim ownership of your resume data. We do not use your individual resume data to train commercial AI models sold to third parties. Aggregated, anonymized insights from usage patterns may be used to improve our service. See our Privacy Policy for complete data handling details.`,
    },
    {
      id: "limitation",
      title: "7. Limitation of Liability",
      content: `To the maximum extent permitted by law, HireForge is not liable for: indirect, incidental, or consequential damages; loss of employment opportunities; decisions made by employers based on your resume; or any damages exceeding the amount you paid for the Service in the past 12 months (which, since HireForge is free, is $0). We provide the Service "as is" without warranties of any kind, express or implied, including but not limited to fitness for a particular purpose.`,
    },
    {
      id: "changes",
      title: "8. Changes to the Service",
      content: `We may modify, suspend, or discontinue any part of HireForge at any time. We will provide at least 30 days notice for material changes that negatively affect users. We will always provide a data export option before any account or data deletion. Our commitment: core resume analysis features will remain free for the foreseeable future.`,
    },
    {
      id: "governing-law",
      title: "9. Governing Law & Disputes",
      content: `These Terms are governed by the laws of India. Any disputes will be resolved through binding arbitration under the Arbitration and Conciliation Act, 1996, before pursuing litigation. For informal resolution, contact us at legal@hireforge.dev — we aim to resolve most issues within 30 days without formal proceedings.`,
    },
    {
      id: "contact-terms",
      title: "10. Contact",
      content: `For questions about these Terms: legal@hireforge.dev\nFor privacy-related questions: privacy@hireforge.dev\nFor general support: hello@hireforge.dev\n\nThese Terms constitute the entire agreement between you and HireForge regarding the Service.`,
    },
  ];

  return (
    <div className="flex flex-col">
      {/* Hero */}
      <section className="relative px-4 pt-16 pb-12 text-center overflow-hidden">
        <div className="container max-w-3xl mx-auto space-y-4 animate-in fade-in slide-in-from-bottom-6 duration-700">
          <div className="inline-flex items-center justify-center p-3 rounded-2xl bg-primary/10">
            <Scale className="h-8 w-8 text-primary" />
          </div>
          <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight">Terms of Service</h1>
          <p className="text-muted-foreground">Effective: {effectiveDate} · Last updated: {lastUpdated}</p>
          <div className="p-4 rounded-2xl bg-green-500/10 border border-green-500/20 text-left max-w-xl mx-auto">
            <p className="text-sm font-medium text-green-700 dark:text-green-400 flex items-start gap-2">
              <CheckCircle2 className="h-4 w-4 mt-0.5 shrink-0" />
              <span><strong>Plain English summary:</strong> You own your data. HireForge is free. We analyze your resume for you, not for us. You can delete everything anytime.</span>
            </p>
          </div>
        </div>
      </section>

      {/* Table of Contents */}
      <section className="px-4 pb-6">
        <div className="container max-w-3xl mx-auto">
          <div className="p-5 rounded-2xl bg-card border">
            <div className="flex items-center gap-2 mb-3">
              <FileText className="h-4 w-4 text-muted-foreground" />
              <h2 className="font-bold text-sm">Table of Contents</h2>
            </div>
            <ol className="space-y-1 text-sm text-muted-foreground list-decimal list-inside grid sm:grid-cols-2 gap-1">
              {sections.map(s => (
                <li key={s.id}>
                  <a href={`#${s.id}`} className="hover:text-foreground transition-colors">{s.title.replace(/^[0-9]+\. /, "")}</a>
                </li>
              ))}
            </ol>
          </div>
        </div>
      </section>

      {/* Sections */}
      <section className="px-4 pb-16">
        <div className="container max-w-3xl mx-auto space-y-5">
          {sections.map(section => (
            <div
              key={section.id}
              id={section.id}
              className={`p-7 rounded-3xl border scroll-mt-24 ${section.highlight === "rights" ? "bg-gradient-to-br from-accent/5 to-card border-accent/20" : "bg-card"}`}
            >
              <h2 className="text-xl font-bold mb-4 flex items-center gap-2">
                {section.highlight === "rights" && <CheckCircle2 className="h-5 w-5 text-accent" />}
                {section.title}
              </h2>
              {section.content && (
                <p className="text-sm text-muted-foreground leading-relaxed whitespace-pre-line">{section.content}</p>
              )}
              {section.items && (
                <div className="space-y-3">
                  {section.items.map(item => (
                    <div key={item.title} className="flex gap-3">
                      <CheckCircle2 className="h-4 w-4 text-green-500 mt-0.5 shrink-0" />
                      <div>
                        <p className="font-medium text-sm">{item.title}</p>
                        <p className="text-sm text-muted-foreground">{item.desc}</p>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          ))}
        </div>
      </section>

      {/* Footer CTA */}
      <section className="py-12 px-4 bg-muted/40">
        <div className="container max-w-3xl mx-auto text-center space-y-4">
          <p className="text-muted-foreground">Questions about these terms? We're human — just ask.</p>
          <div className="flex flex-wrap gap-3 justify-center">
            <Button onClick={() => navigate("/contact")} className="gap-2">
              <Mail className="h-4 w-4" /> Contact Legal Team
            </Button>
            <Button variant="outline" onClick={() => navigate("/privacy")}>
              Privacy Policy
            </Button>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
};

export default TermsOfService;
